name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Run tests
        run: cd frontend && npm run test

      - name: Lint code
        run: cd frontend && npm run lint

      - name: Audit dependencies
        run: cd frontend && npm audit --audit-level=high



  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
        uses: actions/checkout@v3

        - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make mvnw executable
        run: chmod +x backend/mvnw

      - name: Build and test
        run: cd backend && ./mvnw clean verify

      - name: Lint Java code
        run: cd backend && ./mvnw checkstyle:check

      - name: Scan for vulnerabilities
        run: cd backend && ./mvnw org.owasp:dependency-check-maven:check

  deploy:
    name: Deploy (Placeholder)
    needs: [frontend-ci, backend-ci]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: echo "Deploying application..."
